---

collections:
  - name: community.general
  - name: vmware.vmware_rest
  - name: redhat.rhel_system_roles
  - name: jjaswanson4.utilities
  - name: ansible.posix
  - name: redhat.satellite
  - name: community.vmware