---

roles:
  - src: redhat_sap.sap_hostagent
  - src: https://github.com/linux-system-roles/sap-preconfigure.git
  - src: https://github.com/linux-system-roles/sap-hana-preconfigure.git
  - src: https://github.com/linux-system-roles/sap-netweaver-preconfigure.git
  - src: redhat_sap.sap_hana_deployment
  - src: https://github.com/redhat-sap/sap-hana-hsr.git
  - src: redhat_sap.sap_hana_ha_pacemaker
  - src: redhat_sap.sap_s4hana_deployment