---

- name: set persistence in HANA configuration so HSR kicks back in
  hosts:
    - all
  tasks:
    - name: set persistence to normal mode
      shell: >
        source /usr/sap/RHE/home/.sapenv.sh &&
        /usr/sap/{{ sap_hana_deployment_hana_sid }}/HDB{{ sap_hana_deployment_hana_instance_number }}/exe/hdbsql
        -n {{ ansible_hostname }}
        -i {{ sap_hana_deployment_hana_instance_number }}
        -u SYSTEM
        -p {{ sap_hana_deployment_hana_db_system_password }}
        "ALTER SYSTEM ALTER CONFIGURATION ('global.ini', 'SYSTEM') SET ('persistence', 'normal') = 'overwrite' WITH RECONFIGURE";
      become: yes
      become_user: "{{ sap_hana_deployment_hana_sid | lower }}adm"
      become_method: su
      register: db_overwrite_cmd