---

- name: load configuration into ansible controller
  hosts:
    - localhost
  gather_facts: false
  vars:
    ansible_connection: local
  vars_files:
    - vars/ansible-controller-configuration.yml
  pre_tasks:
    - name: Check for organization
      ansible.builtin.uri:
        url: "https://{{tower_hostname }}/api/v2/organizations?search={{ tower_organizations[0].name | regex_replace(' ', '+') }}"
        user: "{{ tower_username }}"
        password: "{{ tower_password }}"
        validate_certs: "{{ tower_validate_certs }}"
        force_basic_auth: yes
      register: organization_search
    - name: create empty organization so credentials can be added to it
      block:
        - name: set organization name fact
          ansible.builtin.set_fact:
            organization_name: SAP S4 HANA Deployment Demo
        - name: create empty organization
          ansible.builtin.include_role:
            name: redhat_cop.tower_configuration.organizations
          vars:
            tower_organizations:
              - name: "{{ organization_name }}"
      when:
        - organization_search.json.count | int != 1  
  roles:
    -  redhat_cop.tower_configuration.credential_types
    - redhat_cop.tower_configuration.credentials
    - redhat_cop.tower_configuration.organizations
    - redhat_cop.tower_configuration.users
    - redhat_cop.tower_configuration.teams
    - redhat_cop.tower_configuration.projects
    - redhat_cop.tower_configuration.inventories
    - redhat_cop.tower_configuration.hosts
    - redhat_cop.tower_configuration.groups
    - redhat_cop.tower_configuration.job_templates
    - redhat_cop.tower_configuration.workflow_job_templates
    - redhat_cop.tower_configuration.tower_role