---

tower_hostname: tower06.lab.msp.redhat.com
tower_validate_certs: no
tower_username: admin
tower_password: "{{ ansible_password }}"

tower_credentials:
  - name: SAP Systems Root Account
    credential_type: Machine
    organization: SAP S4 HANA Deployment Demo
    inputs:
      username: root
      password: "{{ ansible_password }}"
    update_secrets: no
  - name: MSP Lab Automation Hub - RH Certified
    credential_type: Ansible Galaxy/Automation Hub API Token
    organization: Default
    inputs:
      url: https://automationhub01.lab.msp.redhat.com/api/galaxy/content/rh-certified/
      token: "{{ automation_hub_token }}"
    update_secrets: no
  - name: MSP Lab Automation Hub - Community
    credential_type: Ansible Galaxy/Automation Hub API Token
    organization: Default
    inputs:
      url: https://automationhub01.lab.msp.redhat.com/api/galaxy/content/community/
      token: "{{ automation_hub_token }}"
    update_secrets: no

tower_organizations:
  - name: SAP S4 HANA Deployment Demo
    galaxy_credentials:
    - MSP Lab Automation Hub - RH Certified
    - MSP Lab Automation Hub - Community
    - Ansible Galaxy

tower_teams:
  - name: BASIS (Application Team)
    description: SAP BASIS application team
    organization: SAP S4 HANA Deployment Demo
  - name: Infrastructure
    description: Infrastructure team
    organization: SAP S4 HANA Deployment Demo

tower_user_accounts:
  - username: basis_user
    password: "{{ ansible_password }}"
    email: dont@email.me
    update_secrets: no
  - username: infrastructure_user
    password: "{{ ansible_password }}"
    email: dont@email.me
    update_secrets: no

tower_projects:
  - name: SAP S4 HANA Deployment Demo
    organization: SAP S4 HANA Deployment Demo
    scm_branch: main
    scm_type: git
    scm_url: https://github.com/jjaswanson4/s4-hana-deployment-demo.git
    wait: yes

tower_inventories:
  - name: SAP S4 HANA Deployment Demo
    organization: SAP S4 HANA Deployment Demo
    variables: "{{ lookup('file', 'inventory/group_vars/all.yml') | from_yaml }}"

tower_hosts:
  - name: sapddapp1.josh.lab.msp.redhat.com
    inventory: SAP S4 HANA Deployment Demo
    variables: "{{ lookup('file', 'inventory/host_vars/sapddapp1.josh.lab.msp.redhat.com.yml') | from_yaml }}"
  - name: sapddhdb1.josh.lab.msp.redhat.com
    inventory: SAP S4 HANA Deployment Demo
    variables: "{{ lookup('file', 'inventory/host_vars/sapddhdb1.josh.lab.msp.redhat.com.yml') | from_yaml }}"
  - name: sapddhdb2.josh.lab.msp.redhat.com
    inventory: SAP S4 HANA Deployment Demo
    variables: "{{ lookup('file', 'inventory/host_vars/sapddhdb2.josh.lab.msp.redhat.com.yml') | from_yaml }}"

tower_groups:
  - name: hana
    inventory: SAP S4 HANA Deployment Demo
    hosts:
      - sapddhdb1.josh.lab.msp.redhat.com
      - sapddhdb2.josh.lab.msp.redhat.com
    variables: "{{ lookup('file', 'inventory/group_vars/hana.yml') | from_yaml }}"
  - name: s4
    inventory: SAP S4 HANA Deployment Demo
    hosts:
      - sapddapp1.josh.lab.msp.redhat.com
    variables: "{{ lookup('file', 'inventory/group_vars/s4.yml') | from_yaml }}"
  - name: development
    inventory: SAP S4 HANA Deployment Demo
    hosts:
      - sapddapp1.josh.lab.msp.redhat.com
      - sapddhdb1.josh.lab.msp.redhat.com
      - sapddhdb2.josh.lab.msp.redhat.com
    variables: "{{ lookup('file', 'inventory/group_vars/development.yml') | from_yaml }}"
  - name: sap
    inventory: SAP S4 HANA Deployment Demo
    children:
      - hana
      - s4
      - development
    variables: "{{ lookup('file', 'inventory/group_vars/sap.yml') | from_yaml }}"

tower_templates:
  # Infrastructure Team Job Templates
  - name: Pre-Provisioning Tasks
    inventory: SAP S4 HANA Deployment Demo
    project: SAP S4 HANA Deployment Demo
    playbook: playbooks/infrastructure/pre-provisioning.yml
  - name: Provision Tasks
    inventory: SAP S4 HANA Deployment Demo
    project: SAP S4 HANA Deployment Demo
    playbook: playbooks/infrastructure/provision-infrastructure.yml
    credentials:
      - SAP Systems Root Account
  - name: Post-Provisioning Tasks
    inventory: SAP S4 HANA Deployment Demo
    project: SAP S4 HANA Deployment Demo
    playbook: playbooks/infrastructure/post-provisioning.yml
    credentials:
      - SAP Systems Root Account
  - name: Manage Local Storage
    inventory: SAP S4 HANA Deployment Demo
    project: SAP S4 HANA Deployment Demo
    playbook: playbooks/infrastructure/manage-local-storage.yml
    credentials:
      - SAP Systems Root Account
  - name: Manage NFS Shares
    inventory: SAP S4 HANA Deployment Demo
    project: SAP S4 HANA Deployment Demo
    playbook: playbooks/infrastructure/manage-nfs-shares.yml
    credentials:
      - SAP Systems Root Account
  - name: Manage NFS Shares
    inventory: SAP S4 HANA Deployment Demo
    project: SAP S4 HANA Deployment Demo
    playbook: playbooks/infrastructure/manage-dns-records.yml
  # BASIS (Application Team) Job Templates
  - name: SAP Preconfigure Tasks
    inventory: SAP S4 HANA Deployment Demo
    project: SAP S4 HANA Deployment Demo
    playbook: playbooks/basis/sap-preconfigure.yml
    credentials:
      - SAP Systems Root Account
  - name: Netweaver Preconfigure Tasks
    inventory: SAP S4 HANA Deployment Demo
    project: SAP S4 HANA Deployment Demo
    playbook: playbooks/basis/netweaver-preconfigure.yml
    credentials:
      - SAP Systems Root Account
  - name: HANA Preconfigure Tasks
    inventory: SAP S4 HANA Deployment Demo
    project: SAP S4 HANA Deployment Demo
    playbook: playbooks/basis/hana-preconfigure.yml
    credentials:
      - SAP Systems Root Account

tower_workflows:
  # Infrastructure Team Workflows
  - name: Provision Infrastructure
    inventory: SAP S4 HANA Deployment Demo
    organization: SAP S4 HANA Deployment Demo
    extra_vars: "{{ lookup('file', 'extra-vars.yml') | from_yaml }}"
    simplified_workflow_nodes:
      - unified_job_template: Pre-Provisioning Tasks
        identifier: node101
        success_nodes:
          - node102
      - unified_job_template: Provision Tasks
        identifier: node102
        success_nodes:
          - node103
      - unified_job_template: Post-Provisioning Tasks
        identifier: node103
  # BASIS (Application Team) Workflows
  - name: Install SAP S4 HANA Stack
    inventory: SAP S4 HANA Deployment Demo
    organization: SAP S4 HANA Deployment Demo
    extra_vars: "{{ lookup('file', 'extra-vars.yml') | from_yaml }}"
    simplified_workflow_nodes:
      - unified_job_template: Provision Infrastructure
        identifier: node201
        success_nodes:
          - node202
      - unified_job_template: Manage Local Storage
        identifier: node202
        success_nodes:
          - node203
      - unified_job_template: Manage NFS Shares
        identifier: node203
        success_nodes:
          - node204
      - unified_job_template: SAP Preconfigure Tasks
        identifier: node204
        success_nodes:
          - node205
          - node206
      - name: Netweaver Preconfigure Tasks
        identifier: node205
        success_nodes:
          - node207
      - name: HANA Preconfigure Tasks
        identifier: node206
        success_nodes:
          - node207


tower_rbac:
  # Team Membership
  - user: basis_user
    target_team: BASIS (Application Team)
    organization: SAP S4 HANA Deployment Demo
    role: member
  - user: infrastructure_user
    target_team: Infrastructure
    organization: SAP S4 HANA Deployment Demo
    role: member
  # Infrastructure Team Permissions
  - team: Infrastructure
    role: admin
    credential: SAP Systems Root Account
  - team: Infrastructure
    role: admin
    inventory: SAP S4 HANA Deployment Demo
  - team: Infrastructure
    role: admin
    project: SAP S4 HANA Deployment Demo
  - team: Infrastructure
    role: admin
    job_template: Pre-Provisioning Tasks
  - team: Infrastructure
    role: admin
    job_template: Provision Tasks
  - team: Infrastructure
    role: admin
    job_template: Post-Provisioning Tasks
  - team: Infrastructure
    role: admin
    job_template: Manage NFS Shares
  - team: Infrastructure
    role: admin
    job_template: Manage Local Storage
  - team: Infrastructure
    role: admin
    workflow: Provision Infrastructure
  # BASIS (Application Team) Permissions for Infrastructure Automation
  - team: BASIS (Application Team)
    role: read
    inventory: SAP S4 HANA Deployment Demo
  - team: BASIS (Application Team)
    role: admin
    project: SAP S4 HANA Deployment Demo
  - team: BASIS (Application Team)
    role: execute
    job_template: Manage NFS Shares
  - team: BASIS (Application Team)
    role: execute
    job_template: Manage DNS Records
  - team: BASIS (Application Team)
    role: execute
    job_template: Manage Local Storage
  - team: BASIS (Application Team)
    role: execute
    workflow: Provision Infrastructure
  # BASIS (Application Team) Permissions
  - team: BASIS (Application Team)
    role: admin
    job_template: SAP Preconfigure Tasks
  - team: BASIS (Application Team)
    role: admin
    job_template: Netweaver Preconfigure Tasks
  - team: BASIS (Application Team)
    role: admin
    job_template: HANA Preconfigure Tasks    